In [1]:
model_yaml_path=r"C:\Users\1672040\Desktop\project\Energy efficiency\yaml_files\model.yaml"

In [2]:
from Energy_efficiency.entity.model_factory import ModelFactory
model_factory=ModelFactory(model_config_path=model_yaml_path)

In [3]:
model_list=model_factory.get_initialized_model_list()

{'fit_intercept': True}
{'min_samples_leaf': 3, 'bootstrap': True, 'min_samples_split': 2, 'n_estimators': 200}


In [4]:
model_list

[InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression'),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=3, n_estimators=200), param_grid_search={'min_samples_leaf': [1, 2, 4], 'min_samples_split': [2, 5, 10], 'n_estimators': [200, 400, 600, 800, 1000]}, model_name='sklearn.ensemble.RandomForestRegressor')]

In [88]:
import yaml
with open('yaml_files\model.yaml', 'rb') as yaml_file:
    yaml=yaml.safe_load(yaml_file)

In [89]:
yaml

{'grid_search': {'class': 'GridSearchCV',
  'module': 'sklearn.model_selection',
  'params': {'cv': 5, 'verbose': 2}},
 'model_selection': {'module_0': {'class': 'LinearRegression',
   'module': 'sklearn.linear_model',
   'params': {'fit_intercept': True},
   'search_param_grid': {'fit_intercept': [True, False]}},
  'module_1': {'class': 'RandomForestRegressor',
   'module': 'sklearn.ensemble',
   'params': {'min_samples_leaf': 3,
    'bootstrap': True,
    'min_samples_split': 2,
    'n_estimators': 200},
   'search_param_grid': {'min_samples_leaf': [1, 2],
    'min_samples_split': [2, 5],
    'n_estimators': [200, 400]}}}}

In [86]:
import yaml
with open('yaml_files\schema.yaml', 'rb') as yaml_file:
    yaml=yaml.safe_load(yaml_file)

In [87]:
dict(zip(df.columns,list(map(lambda x:str(x).replace("dtype('","").replace("')","") ,df.dtypes.values))))==yaml['columns']

True

In [1]:
from Energy_efficiency.util.util import load_numpy_array_data,load_object

In [2]:
data_file_path=r"C:\Users\1672040\Desktop\project\Energy efficiency\Energy_efficiency\artifact\data_transformation\2022-07-16-09-48-03\transformed_data\train\cleaned_data.npz"

In [12]:
data=load_numpy_array_data(data_file_path)

In [14]:
x,y=data[:,:-1],data[:,-1]

In [15]:
best_model=model_factory.get_best_model(x,y)

{'fit_intercept': True}
{'min_samples_leaf': 3, 'bootstrap': True, 'min_samples_split': 2, 'n_estimators': 200}
{'cv': 5, 'verbose': 2}
Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=  

[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=800; total time=   1.5s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=800; total time=   1.5s
[CV] END min_samples_leaf=2, min_samples_split=2, n_estimators=800; total time=   1.5s
[CV] END min_samples_leaf=2, min_samples_sp

[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=400; total time=   0.6s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=400; total time=   0.7s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=600; total time=   1.0s
[CV] END min_samples_leaf=4, min_samples_split=5, n_estimators=600; total time=   1.1s
[CV] END min_samples_leaf=4, min_samples_sp

In [21]:
best_model.best_model

RandomForestRegressor(n_estimators=800)

In [22]:
model_factory.grid_searched_best_model_list[1]

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=3, n_estimators=200), best_model=RandomForestRegressor(n_estimators=800), best_parameters={'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 800}, best_score=0.9973024374912889)

In [71]:
path=r"C:\Users\1672040\Desktop\project\Energy_efficiency1\saved_models\20220717145456\model.pkl"

In [72]:
obj=load_object(file_path=path)

c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SimpleImputer from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator StandardScaler from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Pipeline from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Decisi

In [11]:
import pandas as pd
df=pd.read_csv('cleaned_data.csv')

In [12]:
df.iloc[0]

X1      0.98
X2    514.50
X3    294.00
X4    110.25
X5      7.00
X6      2.00
X7      0.00
X8      0.00
Y1     15.55
Y2     21.33
Name: 0, dtype: float64

In [84]:
import numpy as np
test=[[0.97, 514.5, 294.0, 110.25, 8.0, 2.0, 0.0, 1.0]]


In [85]:
obj.predict(test)

(array([20.129325]), array([25.16415]))

In [95]:
from Energy_efficiency.entity.housing_predictor import EnergyPredictor

In [93]:
direc=r"C:\Users\1672040\Desktop\project\Energy_efficiency1\saved_models"

In [94]:
EnergyPredictor(model_dir=direc).predict([[0.97, 514.5, 294.0, 110.25, 8.0, 2.0, 0.0, 1.0]])

c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SimpleImputer from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator StandardScaler from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Pipeline from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Decisi

(array([20.129325]), array([25.16415]))

In [99]:

from Energy_efficiency.constant import *
from Energy_efficiency.util.util import read_yaml_file

In [100]:
config_info=read_yaml_file(file_path=CONFIG_FILE_PATH)

In [102]:
model_pusher_config_info=config_info[MODEL_PUSHER_CONFIG_KEY]
export_dir_path = os.path.join(ROOT_DIR, model_pusher_config_info[MODEL_PUSHER_MODEL_EXPORT_DIR_KEY])

In [103]:
export_dir_path

'C:\\Users\\1672040\\Desktop\\project\\Energy_efficiency1\\saved_models'

In [104]:
from Energy_efficiency.entity.energy_predictor import  Energy_efficiency_Data,EnergyPredictor

In [106]:
test_data=Energy_efficiency_Data(0.97, 514.5, 294.0, 110.25, 8.0, 2.0, 0.0, 1.0).get_energy_input_data_frame()
test_data

X1     X2     X3      X4   X5   X6   X7   X8
0  0.97  514.5  294.0  110.25  8.0  2.0  0.0  1.0

In [109]:
EnergyPredictor(export_dir_path).predict([[0,0,0,0,0,0,0,0]])

c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SimpleImputer from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator StandardScaler from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Pipeline from version 1.0.2 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\1672040\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Decisi

(array([13.6812]), array([16.187]))